name: Test code

on:
  workflow_dispatch:

jobs:
  check:
    name: "Test static code"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Pylint
      run: pip install pylint

    - name: Install Mypy
      run: pip install mypy

    - name: Run Pylint
      run: |
         pylint $(git ls-files '*.py')

    - name: Run Mypy
      run: |
         mypy $(git ls-files '*.py')

  test:
    name: "Test dynamic code"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Pytest
      run: pip install pytest

    - name: Run Pytest (test_handling_string)
      run: |
         pytest -v -s
